# Generated by Django 4.2 on 2023-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='view',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
