# Generated by Django 4.1.2 on 2023-04-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projects_github_projects_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='content',
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(default=None, max_length=300),
        ),
    ]
