# Generated by Django 4.1.2 on 2023-04-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_projects_content_projects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='herramientas_destacadas',
            field=models.CharField(default=None, max_length=140),
        ),
    ]
